#ifndef UTILS_SPRITEDEFINES_H
#define UTILS_SPRITEDEFINES_H
#include <stdint.h>

#define FONT_BLANK_SPACE 32
#define FONT_FILL_A 176
#define FONT_FILL_B 177
#define FONT_FILL_C 178
#define FONT_BORDER_A_TOP_LEFT 179
#define FONT_BORDER_A_TOP 180
#define FONT_BORDER_A_TOP_RIGHT 181
#define FONT_BORDER_A_BOTTOM_LEFT 182
#define FONT_BORDER_A_BOTTOM 183
#define FONT_BORDER_A_BOTTOM_RIGHT 184
#define FONT_BORDER_A_LEFT 185
#define FONT_BORDER_A_RIGHT 186
#define FONT_BORDER_B_TOP_LEFT 187
#define FONT_BORDER_B_TOP 188
#define FONT_BORDER_B_TOP_RIGHT 189
#define FONT_BORDER_B_BOTTOM_LEFT 190
#define FONT_BORDER_B_BOTTOM 191
#define FONT_BORDER_B_BOTTOM_RIGHT 192
#define FONT_BORDER_B_LEFT 193
#define FONT_BORDER_B_RIGHT 194
#define FONT_BORDER_C_TOP_LEFT 195
#define FONT_BORDER_C_TOP 196
#define FONT_BORDER_C_TOP_RIGHT 197
#define FONT_BORDER_C_BOTTOM_LEFT 198
#define FONT_BORDER_C_BOTTOM 199
#define FONT_BORDER_C_BOTTOM_RIGHT 200
#define FONT_BORDER_C_LEFT 201
#define FONT_BORDER_C_RIGHT 202
#define FONT_BORDER_D_TOP_LEFT 203
#define FONT_BORDER_D_TOP 204
#define FONT_BORDER_D_TOP_RIGHT 205
#define FONT_BORDER_D_BOTTOM_LEFT 206
#define FONT_BORDER_D_BOTTOM 207
#define FONT_BORDER_D_BOTTOM_RIGHT 208
#define FONT_BORDER_D_LEFT 209
#define FONT_BORDER_D_RIGHT 210

#endif
